apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-debugger
  labels:
    app: request-debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-debugger
  template:
    metadata:
      labels:
        app: request-debugger
    spec:
      containers:
      - name: http-port
        image: ghcr.io/nadundesilva/tools/request-debugger:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: request-debugger
  labels:
    app: request-debugger
spec:
  selector:
    app: request-debugger
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: http-port
