apiVersion: v1
kind: Service
metadata:
  name: request-debugger
  labels:
    app: request-debugger
  annotations:
    checkov.io/skip1: CKV_K8S_21=Not a production deployment
spec:
  selector:
    app: request-debugger
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: http-port
