apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-debugger
  labels:
    app: request-debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-debugger
  template:
    metadata:
      labels:
        app: request-debugger
    spec:
      containers:
        - name: request-debugger
          image: nadunrds/debug-tools-request-debugger:latest
          ports:
            - name: http-port
              containerPort: 8080
          env:
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8080"
            - name: STATUS_CODE
              value: "200"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: request-debugger
  labels:
    app: request-debugger
spec:
  selector:
    app: request-debugger
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: http-port
