apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-debugger
  labels:
    app: request-debugger
  annotations:
    checkov.io/skip1: CKV_K8S_21=Not a production deployment
    checkov.io/skip2: CKV_K8S_43=Not a production deployment
    checkov.io/skip3: CKV_K8S_14=Not a production deployment
    checkov.io/skip4: CKV2_K8S_6=Not a production deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-debugger
  template:
    metadata:
      labels:
        app: request-debugger
    spec:
      containers:
        - name: request-debugger
          image: nadunrds/debug-tools-request-debugger:latest
          ports:
            - name: http-port
              containerPort: 8080
          env:
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8080"
            - name: STATUS_CODE
              value: "200"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: http-port
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http-port
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            runAsUser: 10000
            runAsGroup: 30000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 10000
        runAsGroup: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: request-debugger
  labels:
    app: request-debugger
  annotations:
    checkov.io/skip1: CKV_K8S_21=Not a production deployment
spec:
  selector:
    app: request-debugger
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: http-port
