apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-container
  labels:
    app: debug-container
  annotations:
    checkov.io/skip1: CKV_K8S_21=Not a production deployment
    checkov.io/skip2: CKV_K8S_43=Not a production deployment
    checkov.io/skip3: CKV_K8S_14=Not a production deployment
    checkov.io/skip4: CKV2_K8S_6=Not a production deployment
    checkov.io/skip5: CKV_K8S_8=Not required since nothing is running
    checkov.io/skip6: CKV_K8S_9=Not required since nothing is running
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-container
  template:
    metadata:
      labels:
        app: debug-container
    spec:
      containers:
        - name: debug-container
          image: nadunrds/debug-tools-debug-container:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            runAsUser: 20000
            runAsGroup: 30000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 20000
        runAsGroup: 30000
        runAsNonRoot: true
