name: Build

on: [push, pull_request]

jobs:
  build-tools:
    name: Build Tools
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    strategy:
      matrix:
        tool: ["request-debugger", "debug-container"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./components/${{ matrix.tool }}
          push: true
          tags: ghcr.io/nadundesilva/tools/request-debugger:latest
