name: Build

on: [push, pull_request]

jobs:
  run-codeql-analysis:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  run-ossar-analysis:
    name: Run OSSAR Analysis
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Run OSSAR
        uses: github/ossar-action@v1
        id: ossar
      - name: Upload OSSAR results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.ossar.outputs.sarifFile }}

  build-tools:
    name: Build Tools
    runs-on: ubuntu-20.04
    needs:
      - run-codeql-analysis
      - run-ossar-analysis
    strategy:
      matrix:
        tool: ["request-debugger", "debug-container"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to the Container registry
        uses: docker/login-action@v1
        with:
          username: nadunrds
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
            install: true
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build & Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./components/${{ matrix.tool }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: nadunrds/debug-tools-${{ matrix.tool }}:latest
